---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        install_recommends: no
        force: yes
        dpkg_options: 'force-confdef,force-confold'
        state: latest
      loop:
        - golang
        - docker.io
        - make

    - name: installs, logs in, and setups tailscale
      shell: |
        set timeout 30
        curl -fsSL https://tailscale.com/install.sh | sh
        tailscaleapikey="$(</root/tailscaleapikey.txt)"
        tailscale login --authkey=$tailscaleapikey
        tailscale up --hostname=homelab-proxy
        exit 0

    - name: get traefik configs
      shell: |
        mkdir /etc/traefik
        wget https://raw.githubusercontent.com/LegitCamper/homelab-proxy/main/traefik/traefik.toml -O /etc/traefik/traefik.toml
        wget https://raw.githubusercontent.com/LegitCamper/homelab-proxy/main/traefik/dynamic.toml -O /etc/traefik/dynamic.toml

    - name: install traefik
      shell: |
        wget https://github.com/traefik/traefik/releases/download/v2.9.6/traefik_v2.9.6_linux_amd64.tar.gz -O traefik.tar.gz
        tar xzvf traefik.tar.gz

        # this is for after release of treafik v3.0
        # git clone https://github.com/traefik/traefik.git
        # cd traefik
        # git pull
        # # Generate UI static files
        # make clean-webui generate-webui
        # # required to merge non-code components into the final binary,
        # # such as the web dashboard/UI
        # go generate
        # # Standard go build
        # go build ./cmd/traefik
        # ~/go/src/github.com/traefik/traefik

    - name: install unattended upgrades
      shell: |
        apt install unattended-upgrades
        sudo apt install apt-config-auto-update

    - name: Start unattended upgrades
      service:
        name: unattended-upgrades
        enabled: true 
        state: started
        daemon_reload: yes        

    - name: copy ansible-pull service
      shell: wget https://raw.githubusercontent.com/LegitCamper/homelab-proxy/main/ansible-pull.service -O /etc/systemd/system/ansible-pull.service

    - name: Start ansible-pull service, if not started
      service:
        name: ansible-pull
        enabled: true 
        state: started
        daemon_reload: yes

    - name: copy traefik service
      shell: wget https://raw.githubusercontent.com/LegitCamper/homelab-proxy/main/traefik.service -O /etc/systemd/system/traefik.service

    - name: Start traefik service, if not started
      service:
        name: traefik
        enabled: true 
        state: started
        daemon_reload: yes