--- 
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Get hostname
      shell: echo $HOSTNAME
      register: result

    - name: install packages
      ansible.builtin.apt:
        pkg:
          - apache2-utils

    - name: traefik container
      community.docker.docker_container:
        name: traefik
        image: traefik:v2.2
        restart_policy: always
        networks:
          - name: web
        exposed_ports:
          - 80
          - 443
        volumes_from:
          # - /var/run/docker.sock:/var/run/docker.sock 
          - ~/.ansible/pull/{{result.stdout}}/traefik.toml:/traefik.toml 
          - ~/.ansible/pull/{{result.stdout}}/traefik_dynamic.toml:/traefik_dynamic.toml 
          - ~/.ansible/pull/{{result.stdout}}/acme.json:/acme.json 

    - name: authelia container
      community.docker.docker_container:
        name: authelia
        image: authelia/authelia
        restart_policy: always
        networks:
          - name: web
        exposed_ports:
          - 80
          - 443
        environment:
          - TZ=America/Denver
        volumes_from:
          - ~/.ansible/pull/{{result.stdout}}/traefik.toml:/traefik.toml 
          - ~/.ansible/pull/{{result.stdout}}/traefik_dynamic.toml:/traefik_dynamic.toml 
          - ~/.ansible/pull/{{result.stdout}}/acme.json:/acme.json 

    - name: installs tailscale
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://tailscale.com/install.sh | sh

  roles:
    - role: hifis.unattended_upgrades
      vars:
        unattended_origins_patterns:
          - origin=Ubuntu,archive=${distro_codename}-security
          - origin=Ubuntu,a=${distro_codename}-updates
        systemd_timer_OnCalendar: "*:0/30"

    - role: dwsr.ansible_pull
      vars:
        ansible_pull_playbook: local.yml
        ansible_pull_inventory: none.yml
        ansible_pull_repo_url: git@github.com:legitcamper/homelab-proxy.git
