[http]
[http.routers]
[http.routers.to-traefik]
rule = "Host(`traefik.sawyer.services`)"
service = "api@internal"
[http.routers.to-dashy]
rule = "Host(`dashy.sawyer.services`)"
service = "dashy"
[http.routers.to-searxng]
rule = "Host(`searxng.sawyer.services`)"
service = "searxng"
[http.routers.to-search]
rule = "Host(`search.sawyer.services`)"
service = "searxng"
[http.routers.to-plex]
rule = "Host(`plex.sawyer.services`)"
service = "plex"
[http.routers.to-transmission]
rule = "Host(`transmission.sawyer.services`)"
service = "transmission"
[http.routers.to-portainer]
rule = "Host(`portainer.sawyer.services`)"
service = "portainer"
[http.routers.to-registry]
rule = "Host(`registry.sawyer.services`)"
service = "registry"
[http.routers.to-github]
rule = "Host(`gh.sawyer.services`)"
service = "github"

[http.services]
[http.services.dashy.loadBalancer]
[[http.services.dashy.loadBalancer.servers]]
url = "http://homelab.dunker-arctic.ts.net:10000"
[http.services.searxng.loadBalancer]
[[http.services.searxng.loadBalancer.servers]]
url = "http://homelab.dunker-arctic.ts.net:9000"
[http.services.plex.loadBalancer]
[[http.services.plex.loadBalancer.servers]]
url = "http://homelab.dunker-arctic.ts.net:32400"
[http.services.transmission.loadBalancer]
[[http.services.transmission.loadBalancer.servers]]
url = "http://homelab.dunker-arctic.ts.net:9091"
[http.services.portainer.loadBalancer]
[[http.services.portainer.loadBalancer.servers]]
url = "http://homelab.dunker-arctic.ts.net:8000"
[http.services.registry.loadBalancer]
[[http.services.registry.loadBalancer.servers]]
url = "http://homelab.dunker-arctic.ts.net:5000"
[http.services.github.loadBalancer]
[[http.services.github.loadBalancer.servers]]
url = "https://github.com/Legitcamper"

[https]
[https.routers]
[https.routers.to-traefik]
rule = "Host(`traefik.sawyer.services`)"
service = "api@internal"
[https.routers.to-dashy]
rule = "Host(`dashy.sawyer.services`)"
service = "dashy"
[https.routers.to-searxng]
rule = "Host(`searxng.sawyer.services`)"
service = "searxng"
[https.routers.to-search]
rule = "Host(`search.sawyer.services`)"
service = "searxng"
[https.routers.to-plex]
rule = "Host(`plex.sawyer.services`)"
service = "plex"
[https.routers.to-transmission]
rule = "Host(`transmission.sawyer.services`)"
service = "transmission"
[https.routers.to-portainer]
rule = "Host(`portainer.sawyer.services`)"
service = "portainer"
[https.routers.to-registry]
rule = "Host(`registry.sawyer.services`)"
service = "registry"
[https.routers.to-github]
rule = "Host(`gh.sawyer.services`)"
service = "github"

[https.services]
[https.services.dashy.loadBalancer]
[[https.services.dashy.loadBalancer.servers]]
url = "https://homelab.dunker-arctic.ts.net:10000"
[https.services.searxng.loadBalancer]
[[https.services.searxng.loadBalancer.servers]]
url = "https://homelab.dunker-arctic.ts.net:9000"
[https.services.plex.loadBalancer]
[[https.services.plex.loadBalancer.servers]]
url = "https://homelab.dunker-arctic.ts.net:32400"
[https.services.transmission.loadBalancer]
[[https.services.transmission.loadBalancer.servers]]
url = "https://homelab.dunker-arctic.ts.net:9091"
[https.services.portainer.loadBalancer]
[[https.services.portainer.loadBalancer.servers]]
url = "https://homelab.dunker-arctic.ts.net:8000"
[https.services.registry.loadBalancer]
[[https.services.registry.loadBalancer.servers]]
url = "https://homelab.dunker-arctic.ts.net:5000"
[https.services.github.loadBalancer]
[[https.services.github.loadBalancer.servers]]
url = "https://github.com/Legitcamper"

[tcp]
[tcp.routers]
[tcp.routers.to-minecraft]
entryPoints = ["minecraft-tcp"]
rule = "HostSNI(`minecraft.sawyer.services`) || HostSNI(`mc.sawyer.services`)"
service = "minecraft"

[tcp.services]
[tcp.services.minecraft.loadBalancer]
[[tcp.services.minecraft.loadBalancer.servers]]
address = "100.103.193.140:25565"

[udp]
[udp.routers]
[udp.routers.to-minecraft]
entryPoints = ["minecraft-udp"]
rule = "HostSNI(`minecraft.sawyer.services`) || HostSNI(`mc.sawyer.services`)"
service = "minecraft"

[udp.services]
[udp.services.minecraft.loadBalancer]
[[udp.services.minecraft.loadBalancer.servers]]
address = "100.103.193.140:25565"
