[http]
[http.routers]
[http.routers.to-traefik]
rule = "Host(`traefik.sawyer.services`)"
service = "traefik"
[http.routers.to-dashy]
rule = "Host(`dashy.sawyer.services`)"
service = "dashy"
[http.routers.to-searxng]
rule = "Host(`searxng.sawyer.services`)"
service = "searxng"

[http.services]
[http.services.traefik.loadBalancer]
[[http.services.traefik.loadBalancer.servers]]
url = "http://127.0.0.1:8080"
[http.services.dashy.loadBalancer]
[[http.services.dashy.loadBalancer.servers]]
url = "http://homelab.dunker-arctic.ts.net:10000"
[http.services.searxng.loadBalancer]
[[http.services.searxng.loadBalancer.servers]]
url = "https://homelab.dunker-arctic.ts.net:9000"

[tcp]
[tcp.routers]
[tcp.routers.to-minecraft]
rule = "Host(`minecraft.sawyer.services`)"
service = "minecraft"

[tcp.services]
[tcp.services.minecraft.loadBalancer]
[[tcp.services.minecraft.loadBalancer.servers]]
url = "https://homelab.dunker-arctic.ts.net:25565"
