[http]
[http.routers]
[http.routers.to-traefik]
rule = "Host(`traefik.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
service = "api@internal"
[http.routers.to-dashy]
rule = "Host(`dashy.sawyer.services`)"
service = "dashy"
[http.routers.to-searxng]
rule = "Host(`searxng.sawyer.services`)"
service = "searxng"

[http.services]
[http.services.dashy.loadBalancer]
[[http.services.dashy.loadBalancer.servers]]
url = "homelab:10000"
[http.services.searxng.loadBalancer]
[[http.services.searxng.loadBalancer.servers]]
url = "homelab:9000"
