[http]
[http.routers]
[http.routers.to-traefik]
rule = "Host(`traefik.sawyer.services`)"
service = "api@internal"
[http.routers.to-dashy]
rule = "Host(`dashy.sawyer.services`)"
service = "dashy"
[http.routers.to-searxng]
rule = "Host(`searxng.sawyer.services`)"
service = "searxng"
[http.routers.to-search]
rule = "Host(`search.sawyer.services`)"
service = "searxng"

[http.services]
[http.services.dashy.loadBalancer]
[[http.services.dashy.loadBalancer.servers]]
url = "http://homelab.dunker-arctic.ts.net:10000"
[http.services.searxng.loadBalancer]
[[http.services.searxng.loadBalancer.servers]]
url = "http://homelab.dunker-arctic.ts.net:9000"

[tcp]
[tcp.routers]
[tcp.routers.to-minecraft]
entryPoints = ["minecraft-tcp"]
rule = "HostSNI(`minecraft.sawyer.services`) || HostSNI(`mc.sawyer.services`)"
service = "minecraft"

[tcp.services]
[tcp.services.minecraft.loadBalancer]
[[tcp.services.minecraft.loadBalancer.servers]]
address = "100.103.193.140:25565"

[udp]
[udp.routers]
[udp.routers.to-minecraft]
entryPoints = ["minecraft-udp"]
rule = "HostSNI(`minecraft.sawyer.services`) || HostSNI(`mc.sawyer.services`)"
service = "minecraft"

[udp.services]
[udp.services.minecraft.loadBalancer]
[[udp.services.minecraft.loadBalancer.servers]]
address = "100.103.193.140:25565"
