http:
  routers:
    to-traefik:
      rule: "Host(`traefik.sawyer.services`) && PathPrefix(`/api`, `/dashboard`)"
      service: traefik
    to-searxng:
      rule: 'Host(`searxng.sawyer.services`)'
      service: searxng
    to-dashy:
      rule: 'Host(`dashy.sawyer.services`)'
      service: dashy

  services:
    traefik:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8080
    searxng:
      loadBalancer:
        servers:
          - url: http://homelab:9000
    dashy:
      loadBalancer:
        servers:
         - url: http://homelab:10000