http:
  routers:
    searxng:
      entryPoints:
        - https
      rule: 'Host(`search.sawyer.services`)'
      service: searxng
    dashy:
      entryPoints:
        - https
      rule: 'Host(`dashy.sawyer.services`)'
      service: dashy
      # middlewares:
        # - "auth"  
    portainer:
      entryPoints:
        - https
      rule: 'Host(`portainer.sawyer.services`)'
      service: portainer
      middlewares:
        - "auth"  

  ## SERVICES ##
  services:
    searxng:
      loadBalancer:
        servers:
          - url: http://homelab:9000
    dashy:
      loadBalancer:
        servers:
          - url: http://homelab:10000
    portainer:
      loadBalancer:
        servers:
          - url: http://homelab:8000

  ## MIDDLEWARES ##
  middlewares:
    # Authelia guard
    auth:
      forwardauth:
        address: http://127.0.0.1:9091/api/verify?rd=https://auth.sawyer.services/
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
  
    # Authelia basic auth guard
    auth-basic:
      forwardauth:
        address: http://127.0.0.1:9091/api/verify?auth=basic
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          X-Forwarded-Proto: "https"
          server: ""
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
 
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305