[api]
dashboard = true
insecure = true

# HTTP
[entryPoints.tcp80]
address = ":80"
[entryPoints.udp80]
address = ":80/udp"
# HTTPS
[entryPoints.tcp443]
address = ":443"
[entryPoints.udp443]
address = ":443/udp"
# DNS
# [entryPoints.tcp53]
# address = ":53"
# [entryPoints.udp53]
# address = ":53/udp"
# MINECRAFT
[entryPoints.tcp25565]
address = ":25565"
[entryPoints.udp25565]
address = ":25565/udp"

[providers]
[providers.file]
directory = "/etc/traefik/"
# [providers.docker]
#allowEmptyServices = true
# watch = true
# endpoint = "unix:///var/run/docker.sock"
# exposedByDefault = true

[serversTransport]
insecureSkipVerify = true

# [certificatesResolvers.myresolver.tailscale]

[experimental]
http3 = true
