[api]
dashboard = true
insecure = true

# HTTP
[entryPoints.web-tcp]
address = ":80"
[entryPoints.web-udp]
address = ":80/udp"
# HTTPS
[entryPoints.https-tcp]
address = ":443"
certResolver = "myresolver"
[entryPoints.https-udp]
address = ":443/udp"
certResolver = "myresolver"
# DNS
# [entryPoints.tcp53]
# address = ":53"
# [entryPoints.udp53]
# address = ":53/udp"
# MINECRAFT
[entryPoints.minecraft-tcp]
address = ":25565"
[entryPoints.minecraft-udp]
address = ":25565/udp"

[providers]
[providers.file]
directory = "/etc/traefik/"
# [providers.docker]
#allowEmptyServices = true
# watch = true
# endpoint = "unix:///var/run/docker.sock"
# exposedByDefault = true

[serversTransport]
insecureSkipVerify = true

# this should be turned on after traefik v3.0 is released
# [certificatesResolvers.myresolver.tailscale]

[experimental]
http3 = true
