[api]
dashboard = true
insecure = true

# HTTP
[entryPoints.web-tcp]
address = ":80"
[entryPoints.web-udp]
address = ":80/udp"
# HTTPS
[entryPoints.https-tcp]
address = ":443"
# certResolver = "myresolver"
[entryPoints.https-udp]
address = ":443/udp"
# certResolver = "myresolver"
# MINECRAFT
[entryPoints.minecraft-tcp]
address = ":25565"
[entryPoints.minecraft-udp]
address = ":25565/udp"
# DNS
# [entryPoints.dns-tcp]
# address = ":53"
# [entryPoints.dns-udp]
# address = ":53/udp"

[providers]
[providers.file]
directory = "/etc/traefik/"

[serversTransport]
insecureSkipVerify = true

# this should be turned on after traefik v3.0 is released
# [certificatesResolvers.myresolver.tailscale]

[experimental]
http3 = true
# [experimental.plugins]
# [experimental.plugins.redirect2https]
# version = "v0.0.7"
# modulename = "github.com/setcy/redirect2https"
