[api]
dashboard = true
insecure = true

# [providers.docker]
#allowEmptyServices = true
# watch = true
# endpoint = "unix:///var/run/docker.sock"
# exposedByDefault = true

# HTTP
[entryPoints.tcp80]
address = ":80"
[entryPoints.udp80]
address = ":80/udp"
# HTTP ALT
[entryPoints.tcp8080]
address = ":8080"
[entryPoints.udp8080]
# HTTPS
[entryPoints.tcp443]
address = ":443"
[entryPoints.udp443]
# DNS
[entryPoints.tcp53]
address = ":53"
[entryPoints.udp53]
# MINECRAFT
[entryPoints.tcp25565]
address = ":25565"
[entryPoints.udp25565]
address = ":25565/udp"

[providers]
[providers.file]
directory = "/etc/traefik/"

[serversTransport]
insecureSkipVerify = true

[certificatesResolvers.myresolver.tailscale]

[experimental]
http3 = true
